insert into chef (first_name, last_name, specialization, hire_date, current_station_id, is_on_shift) values ('Clerissa', 'Fallanche', 'Butcher', '10/13/2025', 6, true);
insert into chef (first_name, last_name, specialization, hire_date, current_station_id, is_on_shift) values ('Norby', 'Grice', 'Poissonnier', '1/16/2026', 1, false);
insert into chef (first_name, last_name, specialization, hire_date, current_station_id, is_on_shift) values ('De witt', 'Murricanes', 'Saucier', '1/9/2026', 9, false);
insert into chef (first_name, last_name, specialization, hire_date, current_station_id, is_on_shift) values ('Kore', 'Bowdrey', 'Butcher', '1/11/2026', 5, false);
insert into chef (first_name, last_name, specialization, hire_date, current_station_id, is_on_shift) values ('Mattias', 'Sponer', 'Line Cook', '10/17/2025', 4, false);
insert into chef (first_name, last_name, specialization, hire_date, current_station_id, is_on_shift) values ('Luise', 'Aumerle', 'Executive Chef', '1/25/2026', 11, false);
insert into chef (first_name, last_name, specialization, hire_date, current_station_id, is_on_shift) values ('Cornie', 'Howick', 'Line Cook', '11/4/2025', 1, true);
insert into chef (first_name, last_name, specialization, hire_date, current_station_id, is_on_shift) values ('Ailee', 'Le Breton De La Vieuville', 'Barista', '6/28/2025', 8, true);
insert into chef (first_name, last_name, specialization, hire_date, current_station_id, is_on_shift) values ('Emlyn', 'Vanetti', 'Saucier', '1/5/2026', 9, false);
insert into chef (first_name, last_name, specialization, hire_date, current_station_id, is_on_shift) values ('Hadlee', 'Jeandillou', 'Butcher', '9/2/2025', 3, true);
insert into chef (first_name, last_name, specialization, hire_date, current_station_id, is_on_shift) values ('Rriocard', 'Emerton', 'Prep Cook', '6/27/2025', 8, false);
insert into chef (first_name, last_name, specialization, hire_date, current_station_id, is_on_shift) values ('Uriah', 'Davidovitz', 'Barista', '3/13/2026', 14, true);
insert into chef (first_name, last_name, specialization, hire_date, current_station_id, is_on_shift) values ('Arthur', 'Raine', 'Executive Chef', '12/1/2025', 14, false);
insert into chef (first_name, last_name, specialization, hire_date, current_station_id, is_on_shift) values ('Fredrika', 'Cashin', 'Poissonnier', '8/9/2025', 5, true);
insert into chef (first_name, last_name, specialization, hire_date, current_station_id, is_on_shift) values ('Monika', 'Babalola', 'Expeditor', '5/7/2025', 4, true);
insert into chef (first_name, last_name, specialization, hire_date, current_station_id, is_on_shift) values ('Maire', 'Deegan', 'Barista', '3/7/2026', 5, false);
insert into chef (first_name, last_name, specialization, hire_date, current_station_id, is_on_shift) values ('Trudi', 'Groundwater', 'Sushi Chef', '3/3/2026', 11, false);
insert into chef (first_name, last_name, specialization, hire_date, current_station_id, is_on_shift) values ('Hildegaard', 'Luty', 'Poissonnier', '4/15/2025', 10, false);
insert into chef (first_name, last_name, specialization, hire_date, current_station_id, is_on_shift) values ('Roselin', 'Cozzi', 'Expeditor', '2/7/2026', 13, true);
insert into chef (first_name, last_name, specialization, hire_date, current_station_id, is_on_shift) values ('Quent', 'Filippo', 'Grill Master', '6/8/2025', 1, false);
insert into chef (first_name, last_name, specialization, hire_date, current_station_id, is_on_shift) values ('Phineas', 'Harbinson', 'Line Cook', '3/25/2025', 12, true);
insert into chef (first_name, last_name, specialization, hire_date, current_station_id, is_on_shift) values ('Derek', 'Stobbs', 'Executive Chef', '4/15/2025', 10, true);
insert into chef (first_name, last_name, specialization, hire_date, current_station_id, is_on_shift) values ('Merci', 'Shrimpton', 'Saucier', '3/16/2026', 13, true);
insert into chef (first_name, last_name, specialization, hire_date, current_station_id, is_on_shift) values ('Land', 'Parkhouse', 'Fry Cook', '10/13/2025', 12, false);
insert into chef (first_name, last_name, specialization, hire_date, current_station_id, is_on_shift) values ('Gannie', 'Kinner', 'Sushi Chef', '11/5/2025', 6, false);
insert into chef (first_name, last_name, specialization, hire_date, current_station_id, is_on_shift) values ('Aveline', 'Cornier', 'Garde Manger', '12/31/2025', 14, true);
insert into chef (first_name, last_name, specialization, hire_date, current_station_id, is_on_shift) values ('Norean', 'Ocklin', 'Sous Chef', '3/13/2026', 3, true);
insert into chef (first_name, last_name, specialization, hire_date, current_station_id, is_on_shift) values ('Desmund', 'Bedbrough', 'Garde Manger', '1/8/2026', 10, false);
insert into chef (first_name, last_name, specialization, hire_date, current_station_id, is_on_shift) values ('Lottie', 'Rosenblum', 'Barista', '3/2/2026', 13, true);
insert into chef (first_name, last_name, specialization, hire_date, current_station_id, is_on_shift) values ('Hermione', 'Knibb', 'Saucier', '12/24/2025', 6, true);
insert into chef (first_name, last_name, specialization, hire_date, current_station_id, is_on_shift) values ('Una', 'Rouby', 'Butcher', '8/21/2025', 12, true);
insert into chef (first_name, last_name, specialization, hire_date, current_station_id, is_on_shift) values ('Tamarah', 'Chatelet', 'Barista', '5/21/2025', 4, false);
insert into chef (first_name, last_name, specialization, hire_date, current_station_id, is_on_shift) values ('Mady', 'Doncaster', 'Sous Chef', '3/10/2026', 14, true);
insert into chef (first_name, last_name, specialization, hire_date, current_station_id, is_on_shift) values ('Inge', 'Krebs', 'Fry Cook', '11/2/2025', 4, true);
insert into chef (first_name, last_name, specialization, hire_date, current_station_id, is_on_shift) values ('Sibella', 'Murie', 'Saucier', '1/24/2026', 2, true);
insert into chef (first_name, last_name, specialization, hire_date, current_station_id, is_on_shift) values ('Anne', 'Cassy', 'Pizzaiolo', '3/25/2025', 13, true);
insert into chef (first_name, last_name, specialization, hire_date, current_station_id, is_on_shift) values ('Jeno', 'Hackley', 'Executive Chef', '11/22/2025', 5, true);
insert into chef (first_name, last_name, specialization, hire_date, current_station_id, is_on_shift) values ('Gwenni', 'Gosney', 'Barista', '7/26/2025', 11, true);
insert into chef (first_name, last_name, specialization, hire_date, current_station_id, is_on_shift) values ('Dewain', 'Epp', 'Barista', '10/11/2025', 12, false);
insert into chef (first_name, last_name, specialization, hire_date, current_station_id, is_on_shift) values ('Reece', 'MacLoughlin', 'Prep Cook', '3/1/2026', 4, false);
insert into chef (first_name, last_name, specialization, hire_date, current_station_id, is_on_shift) values ('Nicholas', 'Hedworth', 'Sous Chef', '7/14/2025', 14, false);
insert into chef (first_name, last_name, specialization, hire_date, current_station_id, is_on_shift) values ('Gladi', 'Pettengell', 'Expeditor', '3/22/2025', 4, false);
insert into chef (first_name, last_name, specialization, hire_date, current_station_id, is_on_shift) values ('Gerome', 'McMorland', 'Barista', '10/6/2025', 12, false);
insert into chef (first_name, last_name, specialization, hire_date, current_station_id, is_on_shift) values ('Mikkel', 'Cake', 'Sous Chef', '5/9/2025', 1, false);
insert into chef (first_name, last_name, specialization, hire_date, current_station_id, is_on_shift) values ('Edy', 'Le Claire', 'Prep Cook', '3/25/2025', 6, true);
insert into chef (first_name, last_name, specialization, hire_date, current_station_id, is_on_shift) values ('Edyth', 'Alliker', 'Grill Master', '10/11/2025', 8, false);
insert into chef (first_name, last_name, specialization, hire_date, current_station_id, is_on_shift) values ('Vivie', 'Bordessa', 'Pastry Chef', '8/9/2025', 1, false);
insert into chef (first_name, last_name, specialization, hire_date, current_station_id, is_on_shift) values ('Monro', 'Durrett', 'Executive Chef', '12/8/2025', 1, false);
insert into chef (first_name, last_name, specialization, hire_date, current_station_id, is_on_shift) values ('Somerset', 'Meddings', 'Prep Cook', '3/9/2026', 14, true);
insert into chef (first_name, last_name, specialization, hire_date, current_station_id, is_on_shift) values ('Maressa', 'Splaven', 'Poissonnier', '8/20/2025', 12, true);
insert into chef (first_name, last_name, specialization, hire_date, current_station_id, is_on_shift) values ('Ryann', 'Shanklin', 'Line Cook', '5/30/2025', 5, false);
insert into chef (first_name, last_name, specialization, hire_date, current_station_id, is_on_shift) values ('Aundrea', 'Verissimo', 'Prep Cook', '6/1/2025', 7, false);
insert into chef (first_name, last_name, specialization, hire_date, current_station_id, is_on_shift) values ('George', 'Daltrey', 'Executive Chef', '11/21/2025', 4, true);
insert into chef (first_name, last_name, specialization, hire_date, current_station_id, is_on_shift) values ('Dierdre', 'Praundlin', 'Line Cook', '11/24/2025', 10, false);
insert into chef (first_name, last_name, specialization, hire_date, current_station_id, is_on_shift) values ('Emanuele', 'Biddlestone', 'Sushi Chef', '4/4/2025', 12, false);
insert into chef (first_name, last_name, specialization, hire_date, current_station_id, is_on_shift) values ('Mira', 'Drayson', 'Grill Master', '2/17/2026', 6, true);
insert into chef (first_name, last_name, specialization, hire_date, current_station_id, is_on_shift) values ('Vidovic', 'Sayward', 'Barista', '2/27/2026', 12, false);
insert into chef (first_name, last_name, specialization, hire_date, current_station_id, is_on_shift) values ('Read', 'Plan', 'Grill Master', '3/12/2026', 14, false);
insert into chef (first_name, last_name, specialization, hire_date, current_station_id, is_on_shift) values ('Cassi', 'Yakuntsov', 'Barista', '7/10/2025', 5, false);
insert into chef (first_name, last_name, specialization, hire_date, current_station_id, is_on_shift) values ('Melanie', 'Stawell', 'Saucier', '10/1/2025', 2, true);
