-- 1. Stations
CREATE TABLE kitchen_station (
    station_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    station_name VARCHAR(100) NOT NULL,
    description TEXT,
    is_active BOOLEAN DEFAULT TRUE
);

-- 2. Chefs
CREATE TABLE chef (
    chef_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    specialization VARCHAR(100),
    hire_date DATE NOT NULL,
    current_station_id INT REFERENCES kitchen_station(station_id),
    is_on_shift BOOLEAN DEFAULT FALSE
);

-- 3. Kitchen Orders
-- Note: order_id references the general order table (from another department)
CREATE TABLE kitchen_order (
    kitchen_order_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id INT NOT NULL, 
    status VARCHAR(30) NOT NULL CHECK (status IN ('Pending', 'In-Prep', 'Ready', 'Served', 'Cancelled')),
    start_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    finish_time TIMESTAMP,
    station_id INT REFERENCES kitchen_station(station_id)
);

-- 4. Preparation Tasks
CREATE TABLE preparation_task (
    task_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kitchen_order_id INT REFERENCES kitchen_order(kitchen_order_id),
    chef_id INT REFERENCES chef(chef_id),
    task_description TEXT NOT NULL,
    status VARCHAR(50) DEFAULT 'Pending',
    priority_level INT DEFAULT 1 CHECK (priority_level BETWEEN 1 AND 5)
);

-- 5. Hygiene & Safety Inspections
CREATE TABLE hygiene_inspection (
    inspection_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    station_id INT REFERENCES kitchen_station(station_id) NOT NULL,
    inspector_id INT REFERENCES chef(chef_id) NOT NULL,
    inspection_date DATE DEFAULT CURRENT_DATE,
    next_inspection_date DATE,
    cleanliness_score INT CHECK (cleanliness_score BETWEEN 1 AND 10),
    temperature_check NUMERIC(5,2), -- Numeric with precision as requested
    status VARCHAR(20) NOT NULL, 
    comments TEXT
);

-- 6. Food Prep Log
-- Note: menu_item_id references the menu table (from another department)
CREATE TABLE food_prep_log (
    log_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chef_id INT REFERENCES chef(chef_id) NOT NULL,
    menu_item_id INT NOT NULL, 
    preparation_time INT NOT NULL, 
    prep_date DATE DEFAULT CURRENT_DATE,
    notes TEXT
);