-- 1. Stations
CREATE TABLE kitchen_station (
    station_id      INT          GENERATED BY DEFAULT AS IDENTITY,
    station_name    VARCHAR(100) NOT NULL,
    description     TEXT,
    is_active       BOOLEAN      DEFAULT TRUE,

    CONSTRAINT pk_kitchen_station PRIMARY KEY (station_id)
);

-- 2. Chefs
CREATE TABLE chef (
    chef_id            INT          GENERATED BY DEFAULT AS IDENTITY,
    first_name         VARCHAR(100) NOT NULL,
    last_name          VARCHAR(100) NOT NULL,
    specialization     VARCHAR(100),
    hire_date          DATE         NOT NULL,
    current_station_id INT,
    is_on_shift        BOOLEAN      DEFAULT FALSE,

    CONSTRAINT pk_chef                    PRIMARY KEY (chef_id),
    CONSTRAINT fk_chef_station            FOREIGN KEY (current_station_id)
                                              REFERENCES kitchen_station(station_id)
);

-- 3. Kitchen Orders
CREATE TABLE kitchen_order (
    kitchen_order_id INT          GENERATED BY DEFAULT AS IDENTITY,
    order_id         INT          NOT NULL,
    status           VARCHAR(30)  NOT NULL,
    start_time       TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    finish_time      TIMESTAMP,
    station_id       INT,

    CONSTRAINT pk_kitchen_order           PRIMARY KEY (kitchen_order_id),
    CONSTRAINT chk_kitchen_order_status   CHECK (status IN ('Pending', 'In-Prep', 'Ready', 'Served', 'Cancelled')),
    CONSTRAINT fk_kitchen_order_station   FOREIGN KEY (station_id)
                                              REFERENCES kitchen_station(station_id)
);

-- 4. Preparation Tasks
CREATE TABLE preparation_task (
    task_id          INT          GENERATED BY DEFAULT AS IDENTITY,
    kitchen_order_id INT,
    chef_id          INT,
    task_description TEXT         NOT NULL,
    status           VARCHAR(50)  DEFAULT 'Pending',
    priority_level   INT          DEFAULT 1,

    CONSTRAINT pk_preparation_task        PRIMARY KEY (task_id),
    CONSTRAINT fk_prep_task_order         FOREIGN KEY (kitchen_order_id)
                                              REFERENCES kitchen_order(kitchen_order_id),
    CONSTRAINT fk_prep_task_chef          FOREIGN KEY (chef_id)
                                              REFERENCES chef(chef_id),
    CONSTRAINT chk_prep_task_priority     CHECK (priority_level BETWEEN 1 AND 5)
);

-- 5. Hygiene & Safety Inspections
CREATE TABLE hygiene_inspection (
    inspection_id        INT          GENERATED BY DEFAULT AS IDENTITY,
    station_id           INT          NOT NULL,
    inspector_id         INT          NOT NULL,
    inspection_date      DATE         DEFAULT CURRENT_DATE,
    next_inspection_date DATE,
    cleanliness_score    NUMERIC(4,1),
    temperature_check    NUMERIC(5,2),
    status               VARCHAR(50)  NOT NULL,
    comments             TEXT,

    CONSTRAINT pk_hygiene_inspection      PRIMARY KEY (inspection_id),
    CONSTRAINT fk_inspection_station      FOREIGN KEY (station_id)
                                              REFERENCES kitchen_station(station_id),
    CONSTRAINT fk_inspection_inspector    FOREIGN KEY (inspector_id)
                                              REFERENCES chef(inspector_id),
    CONSTRAINT chk_inspection_score      CHECK (cleanliness_score BETWEEN 1.0 AND 10.0),
    CONSTRAINT chk_inspection_status     CHECK (status IN (
                                              'Perfect condition', 'All clean',
                                              'Passed inspection', 'Needs improvement',
                                              'Fridge slightly warm', 'Good'))
);

-- 6. Food Prep Log
CREATE TABLE food_prep_log (
    log_id           INT  GENERATED BY DEFAULT AS IDENTITY,
    chef_id          INT  NOT NULL,
    menu_item_id     INT  NOT NULL,
    preparation_time INT  NOT NULL,
    prep_date        DATE DEFAULT CURRENT_DATE,
    notes            TEXT,

    CONSTRAINT pk_food_prep_log           PRIMARY KEY (log_id),
    CONSTRAINT fk_food_prep_log_chef      FOREIGN KEY (chef_id)
                                              REFERENCES chef(chef_id)
);
